/**
 * CLI integration tests — run the real bin via child_process in a temp dir.
 *
 * Covers: opt-in side outputs + marker protection, bad config → exit 1,
 * absolute -o, blade globs, negation globs, safelist, --json, --quiet,
 * NO_COLOR, init (.mjs vs .js), and `./cli` import having no side effects.
 */
import { describe, it, beforeEach, afterEach } from 'node:test';
import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import { mkdtempSync, rmSync, writeFileSync, mkdirSync, existsSync, readFileSync } from 'fs';
import { tmpdir } from 'os';
import { join, dirname, resolve } from 'path';
import { fileURLToPath } from 'url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..', '..');
const BIN = join(root, 'src', 'cli', 'index.js');

function run(args, cwd, env = {}) {
  const res = spawnSync(process.execPath, [BIN, ...args], {
    cwd,
    encoding: 'utf-8',
    env: { ...process.env, NO_COLOR: '1', FORCE_COLOR: '0', ...env }
  });
  return { code: res.status, stdout: res.stdout || '', stderr: res.stderr || '' };
}

const VALID_HTML = '<div layout="flex" space="p:medium" visual="bg:primary">ok</div>';
const INVALID_HTML = '<div layout="flex totally_bogus" space="p:medium">bad</div>';

describe('CLI (child_process)', () => {
  let dir;
  beforeEach(() => { dir = mkdtempSync(join(tmpdir(), 'sscss-cli-')); });
  afterEach(() => rmSync(dir, { recursive: true, force: true }));

  const write = (p, c) => { mkdirSync(dirname(join(dir, p)), { recursive: true }); writeFileSync(join(dir, p), c); };

  it('default build does NOT write .cursorrules or types/senang.d.ts (opt-in)', () => {
    write('index.html', VALID_HTML);
    write('senangstart.config.mjs', `export default { content: ['./**/*.html'], output: { css: './out.css' } }`);
    const r = run(['build'], dir);
    assert.equal(r.code, 0, r.stderr);
    assert.ok(existsSync(join(dir, 'out.css')));
    assert.ok(!existsSync(join(dir, '.cursorrules')), '.cursorrules must not be created by default');
    assert.ok(!existsSync(join(dir, 'types', 'senang.d.ts')), 'types/senang.d.ts must not be created by default');
  });

  it('opt-in aiContext output is written with a marker and refuses to clobber user files', () => {
    write('index.html', VALID_HTML);
    write('senangstart.config.mjs', `export default { content: ['./**/*.html'], output: { css: './out.css', aiContext: './.cursorrules' } }`);

    let r = run(['build'], dir);
    assert.equal(r.code, 0, r.stderr);
    const generated = readFileSync(join(dir, '.cursorrules'), 'utf-8');
    assert.ok(generated.startsWith('# generated by SenangStart CSS'), 'generated file must start with marker');

    // Re-running overwrites our own generated file fine
    r = run(['build'], dir);
    assert.equal(r.code, 0);

    // A user-owned file (no marker) is protected
    writeFileSync(join(dir, '.cursorrules'), 'MY OWN RULES\n');
    r = run(['build'], dir);
    assert.equal(r.code, 0, 'CSS build still succeeds (exit 0)');
    assert.equal(readFileSync(join(dir, '.cursorrules'), 'utf-8'), 'MY OWN RULES\n', 'user file must be untouched');
    assert.match(r.stderr, /refusing to overwrite/i);
    assert.match(r.stderr, /\.cursorrules/);
  });

  it('explicit --config that is missing → exit 1 with a clear error', () => {
    write('index.html', VALID_HTML);
    const r = run(['build', '--config', 'nope.config.js'], dir);
    assert.equal(r.code, 1);
    assert.match(r.stderr, /Config file not found/);
    assert.ok(!existsSync(join(dir, 'public', 'senangstart.css')), 'must not silently build with defaults');
  });

  it('auto-discovered config with a syntax error → exit 1 (never silently uses defaults)', () => {
    write('index.html', VALID_HTML);
    write('senangstart.config.js', 'export default { content: [ // broken');
    const r = run(['build'], dir);
    assert.equal(r.code, 1);
    assert.match(r.stderr, /Failed to load config/);
    assert.ok(!existsSync(join(dir, 'public', 'senangstart.css')));
  });

  it('config with wrong types → exit 1 and lists the problems', () => {
    write('index.html', VALID_HTML);
    write('senangstart.config.mjs', `export default { content: './**/*.html', output: { minify: 'yes' } }`);
    const r = run(['build'], dir);
    assert.equal(r.code, 1);
    assert.match(r.stderr, /Invalid config/);
    assert.match(r.stderr, /content: expected an array/);
    assert.match(r.stderr, /output\.minify/);
  });

  it('config outside cwd (absolute --config) works', () => {
    write('proj/index.html', VALID_HTML);
    write('cfg/my.config.mjs', `export default { content: ['./**/*.html'], output: { css: './built.css' } }`);
    const r = run(['build', '--config', join(dir, 'cfg', 'my.config.mjs')], join(dir, 'proj'));
    assert.equal(r.code, 0, r.stderr);
    assert.ok(existsSync(join(dir, 'proj', 'built.css')));
  });

  it('-o accepts absolute paths', () => {
    write('index.html', VALID_HTML);
    const target = join(dir, 'elsewhere', 'deep', 'styles.css');
    const r = run(['build', '-o', target], dir);
    assert.equal(r.code, 0, r.stderr);
    assert.ok(existsSync(target));
    assert.ok(readFileSync(target, 'utf-8').includes('display: flex'));
  });

  it('matches *.blade.php in nested dirs', () => {
    write('resources/views/layouts/app.blade.php', '<main layout="grid" space="g:small">@yield("x")</main>');
    write('senangstart.config.mjs', `export default { content: ['./resources/**/*.blade.php'], output: { css: './out.css' }, preflight: false }`);
    const r = run(['build'], dir);
    assert.equal(r.code, 0, r.stderr);
    const css = readFileSync(join(dir, 'out.css'), 'utf-8');
    assert.ok(css.includes('display: grid'));
    assert.ok(css.includes('gap'));
  });

  it('honours negation globs', () => {
    write('index.html', VALID_HTML);
    write('legacy/old.html', INVALID_HTML);
    write('senangstart.config.mjs', `export default { content: ['./**/*.html', '!./legacy/**'], output: { css: './out.css' } }`);
    const r = run(['build'], dir);
    assert.equal(r.code, 0, `negated file with invalid token should be excluded:\n${r.stderr}`);
    assert.match(r.stdout, /Found 1 source file/);
  });

  it('appends safelist tokens (config + --safelist)', () => {
    write('index.html', '<div layout="flex">x</div>');
    write('senangstart.config.mjs', `export default { content: ['./**/*.html'], output: { css: './out.css' }, preflight: false, safelist: ['visual=bg:primary', { attr: 'space', tokens: ['p:big'] }] }`);
    const r = run(['build', '--safelist', 'g:small', 'visual=text:white'], dir);
    assert.equal(r.code, 0, r.stderr);
    const css = readFileSync(join(dir, 'out.css'), 'utf-8');
    assert.ok(css.includes('[visual~="bg:primary"]') || css.includes('bg:primary'), 'config safelist visual token');
    assert.ok(css.includes('p:big'), 'config safelist object token');
    assert.ok(css.includes('g:small'), '--safelist token');
    assert.ok(css.includes('text:white'), '--safelist explicit attr token');
  });

  it('invalid tokens → exit 1 with file:line diagnostics; --ignore-invalid → exit 0 warnings', () => {
    write('pages/bad.html', `<p>\n\n<div layout="flex totally_bogus">bad</div>`);
    write('senangstart.config.mjs', `export default { content: ['./**/*.html'], output: { css: './out.css' } }`);
    let r = run(['build'], dir);
    assert.equal(r.code, 1);
    assert.match(r.stderr, /pages\/bad\.html:3 totally_bogus \(layout\) → /);
    assert.match(r.stderr, /1 error found in source/);
    assert.ok(existsSync(join(dir, 'out.css')), 'CSS is still written');

    r = run(['build', '--ignore-invalid'], dir);
    assert.equal(r.code, 0);
    assert.match(r.stderr, /1 warning found in source/);
  });

  it('--json prints a machine-readable summary on stdout and nothing else', () => {
    write('index.html', INVALID_HTML);
    write('senangstart.config.mjs', `export default { content: ['./**/*.html'], output: { css: './out.css' } }`);
    const r = run(['build', '--json'], dir);
    assert.equal(r.code, 1);
    const summary = JSON.parse(r.stdout);
    assert.equal(summary.ok, false);
    assert.equal(summary.fileCount, 1);
    assert.deepEqual(summary.files, ['index.html']);
    assert.equal(summary.outputs.css, 'out.css');
    assert.equal(summary.errors.length, 1);
    assert.equal(summary.errors[0].raw, 'totally_bogus');
    assert.equal(summary.errors[0].file, 'index.html');
    assert.equal(typeof summary.durationMs, 'number');
    assert.equal(r.stderr.trim(), '', 'json mode must not print human logs');
  });

  it('--json with a config error prints a JSON error document', () => {
    write('index.html', VALID_HTML);
    const r = run(['build', '--json', '--config', 'missing.js'], dir);
    assert.equal(r.code, 1);
    const doc = JSON.parse(r.stdout);
    assert.equal(doc.ok, false);
    assert.equal(doc.error.code, 'CONFIG_NOT_FOUND');
  });

  it('--quiet prints only errors; output has no ANSI codes under NO_COLOR', () => {
    write('index.html', VALID_HTML);
    let r = run(['build', '--quiet', '-o', 'out.css'], dir);
    assert.equal(r.code, 0);
    assert.equal(r.stdout.trim(), '');
    // eslint-disable-next-line no-control-regex
    const ansi = /\x1b\[/;
    r = run(['build', '-o', 'out.css'], dir);
    assert.ok(!ansi.test(r.stdout) && !ansi.test(r.stderr), 'no ANSI codes when NO_COLOR is set');
    assert.match(r.stdout, /Generated out\.css/);
  });

  it('no config and no files → exit 1 with a clear error', () => {
    const r = run(['build'], dir);
    assert.equal(r.code, 1);
    assert.match(r.stderr, /No source files found/);
  });

  it('init writes senangstart.config.mjs by default and .js in ESM packages', () => {
    let r = run(['init'], dir);
    assert.equal(r.code, 0, r.stderr);
    assert.ok(existsSync(join(dir, 'senangstart.config.mjs')));
    const template = readFileSync(join(dir, 'senangstart.config.mjs'), 'utf-8');
    for (const field of ['safelist', 'prefix', 'layers', 'aiContext: null', 'typescript: null', 'exposeAll', 'extend']) {
      assert.ok(template.includes(field), `template must mention ${field}`);
    }
    // Existing config → warn, no overwrite
    r = run(['init'], dir);
    assert.match(r.stderr, /already exists/);

    const esm = mkdtempSync(join(tmpdir(), 'sscss-esm-'));
    try {
      writeFileSync(join(esm, 'package.json'), '{"type":"module"}');
      r = run(['init'], esm);
      assert.equal(r.code, 0);
      assert.ok(existsSync(join(esm, 'senangstart.config.js')));
      assert.ok(!existsSync(join(esm, 'senangstart.config.mjs')));
    } finally {
      rmSync(esm, { recursive: true, force: true });
    }
  });

  it('the generated init template is a valid config that builds', () => {
    run(['init'], dir);
    write('index.html', VALID_HTML);
    const r = run(['build', '-o', 'out.css'], dir);
    assert.equal(r.code, 0, r.stderr);
  });

  it('importing ./cli (program.js) has no side effects', () => {
    const res = spawnSync(process.execPath, ['-e', `
      import('${join(root, 'src', 'cli', 'program.js').split('\\').join('/')}').then(m => {
        console.log(JSON.stringify({ hasProgram: typeof m.program?.parse === 'function', hasFactory: typeof m.createProgram === 'function', cmds: m.program.commands.map(c => c.name()) }));
      });
    `], { cwd: dir, encoding: 'utf-8', env: { ...process.env, NO_COLOR: '1' } });
    assert.equal(res.status, 0, res.stderr);
    const info = JSON.parse(res.stdout.trim());
    assert.equal(info.hasProgram, true);
    assert.equal(info.hasFactory, true);
    assert.deepEqual(info.cmds.sort(), ['build', 'convert', 'dev', 'init']);
    assert.ok(!existsSync(join(dir, 'public')), 'importing must not build anything');
  });

  it('--version prints the package version', () => {
    const pkg = JSON.parse(readFileSync(join(root, 'package.json'), 'utf-8'));
    const r = run(['--version'], dir);
    assert.equal(r.stdout.trim(), pkg.version);
  });
});
