/**
 * SenangStart CSS - Node.js I/O Utilities
 * Node-specific helper functions (not for browser use)
 */

import { relative, isAbsolute } from 'path';

/**
 * Read file with timeout protection
 * @param {string} filePath - Path to file
 * @param {number} timeoutMs - Timeout in milliseconds
 * @returns {Promise<string>} - File contents
 * @throws {Error} - On timeout or read failure
 */
export async function readFileWithTimeout(filePath, timeoutMs = 5000) {
  const { promises: fsPromises } = await import('fs');

  // Check file size first (async)
  let fileSize;
  try {
    const stats = await fsPromises.stat(filePath);
    fileSize = stats.size;

    // Reject files larger than 10MB
    const MAX_FILE_SIZE = 10 * 1024 * 1024; // 10MB
    if (fileSize > MAX_FILE_SIZE) {
      throw new Error(`File too large: ${filePath} (${Math.round(fileSize / 1024)}KB)`);
    }
  } catch (error) {
    throw new Error(`Cannot stat file: ${filePath} - ${error.message}`);
  }

  return new Promise((resolve, reject) => {
    const timeout = setTimeout(() => {
      reject(new Error(`Read timeout for ${filePath} (exceeded ${timeoutMs}ms)`));
    }, timeoutMs);

    fsPromises.readFile(filePath, 'utf-8')
      .then((content) => {
        clearTimeout(timeout);
        resolve(content);
      })
      .catch((error) => {
        clearTimeout(timeout);
        reject(new Error(`Cannot read file: ${filePath} - ${error.message}`));
      });
  });
}

/**
 * Batch read multiple files with timeout protection
 * Errors are caught per-file and returned in the result's `error` property,
 * allowing callers to handle partial failures gracefully.
 * @param {Array<string>} filePaths - Paths to files
 * @param {number} timeoutMs - Timeout per file
 * @returns {Promise<Array<{path: string, content: string|null, error: Error|null}>>} - File contents with per-file error info
 */
export async function readMultipleFilesWithTimeout(filePaths, timeoutMs = 5000) {
  const results = [];

  // Read files in batches for concurrency without overwhelming the system
  const BATCH_SIZE = 50;

  for (let i = 0; i < filePaths.length; i += BATCH_SIZE) {
    const batch = filePaths.slice(i, i + BATCH_SIZE);

    const batchPromises = batch.map(async (filePath) => {
      try {
        const content = await readFileWithTimeout(filePath, timeoutMs);
        return { path: filePath, content, error: null };
      } catch (error) {
        return { path: filePath, content: null, error };
      }
    });

    const batchResults = await Promise.all(batchPromises);
    results.push(...batchResults);
  }

  return results;
}

/**
 * Check whether a resolved path is safely contained within the given root.
 * Uses path.relative so sibling directories (e.g. /app vs /app-evil) don't
 * pass a startsWith check. Case-insensitive on Windows.
 * @param {string} resolvedPath - Absolute resolved path to check
 * @param {string} root - Absolute root directory
 * @returns {boolean} - True if strictly inside root (root itself → false)
 */
export function isPathInsideRoot(resolvedPath, root) {
  const rel = relative(root, resolvedPath);
  if (rel === '' || isAbsolute(rel)) return false;
  if (process.platform === 'win32') {
    return !rel.toLowerCase().startsWith('..');
  }
  return !rel.startsWith('..');
}

/**
 * Marker line embedded in every generated side-output so the CLI can tell
 * its own files apart from user-owned files with the same name.
 */
export const GENERATED_MARKERS = Object.freeze({
  /** For CSS / TypeScript / JS style files */
  block: '/* generated by SenangStart CSS — do not edit */',
  /** For markdown / .cursorrules / dotfiles */
  hash: '# generated by SenangStart CSS — do not edit'
});

/**
 * Pick the marker style for a given file path.
 * @param {string} filePath
 * @returns {string}
 */
export function markerFor(filePath) {
  const lower = String(filePath).toLowerCase();
  if (/\.(ts|mts|cts|js|mjs|cjs|css|scss|less)$/.test(lower)) return GENERATED_MARKERS.block;
  return GENERATED_MARKERS.hash;
}

/**
 * Does the content carry a generated-file marker (checked in the first 5 lines)?
 * @param {string} content
 * @returns {boolean}
 */
export function hasGeneratedMarker(content) {
  if (typeof content !== 'string') return false;
  const head = content.split(/\r?\n/, 5).join('\n');
  return head.includes('generated by SenangStart CSS');
}

/**
 * Ensure the parent directory of a file exists.
 * @param {string} filePath
 */
export async function ensureDir(filePath) {
  const { promises: fsPromises } = await import('fs');
  const { dirname } = await import('path');
  await fsPromises.mkdir(dirname(filePath), { recursive: true });
}

/**
 * Write a generated file, refusing to overwrite a pre-existing file that does
 * NOT carry the generated marker (i.e. a user-owned file).
 *
 * @param {string} filePath - Absolute output path
 * @param {string} content - Content WITHOUT marker (marker is prepended)
 * @param {{ marker?: string }} [options]
 * @returns {Promise<{ written: boolean, skipped: boolean, reason?: string, path: string }>}
 */
export async function writeGeneratedFile(filePath, content, options = {}) {
  const { promises: fsPromises } = await import('fs');
  const marker = options.marker || markerFor(filePath);

  let existing = null;
  try {
    existing = await fsPromises.readFile(filePath, 'utf-8');
  } catch (error) {
    if (error.code !== 'ENOENT') {
      return { written: false, skipped: true, path: filePath, reason: `cannot read existing file: ${error.message}` };
    }
  }

  if (existing !== null && !hasGeneratedMarker(existing)) {
    return {
      written: false,
      skipped: true,
      path: filePath,
      reason: 'file exists and was not generated by SenangStart CSS (missing marker header); refusing to overwrite'
    };
  }

  await ensureDir(filePath);
  const body = content.startsWith(marker) ? content : `${marker}\n${content}`;
  await fsPromises.writeFile(filePath, body, 'utf-8');
  return { written: true, skipped: false, path: filePath };
}

export default {
  readFileWithTimeout,
  readMultipleFilesWithTimeout,
  ensureDir,
  writeGeneratedFile,
  isPathInsideRoot,
  hasGeneratedMarker,
  markerFor,
  GENERATED_MARKERS
};
