/**
 * SenangStart CSS Configuration
 * @see https://bookklik-technologies.github.io/senangstart-css/guide/configuration
 *
 * This file is ESM. `senangstart init` names it `.mjs` unless your package.json
 * has "type": "module" (then `.js` works too). JSON (`senangstart.config.json`)
 * and TypeScript (`senangstart.config.ts`, Node ≥ 22.18 with type stripping) are
 * also supported.
 */

/** @type {import('@bookklik/senangstart-css/node').Config} */
export default {
  // Files to scan for SenangStart attributes. Globs are resolved relative to
  // the project root. Negation is supported: '!./legacy/**'.
  // node_modules, .git and dist are ignored automatically.
  content: [
    './**/*.html',
    './**/*.{php,blade.php}',
    './src/**/*.{js,jsx,ts,tsx,vue,svelte,astro}'
  ],

  // Tokens to always emit even when not found in `content`.
  //   'flex'                      → attribute inferred (layout)
  //   'visual=bg:primary'         → explicit attribute
  //   { attr: 'space', tokens: ['p:medium', 'g:small'] }
  safelist: [],

  // Reserved for the variant engine: prefix for generated attribute selectors.
  prefix: '',

  // Wrap output in cascade layers (@layer) for predictable ordering.
  layers: true,

  // Output configuration
  output: {
    css: './public/senangstart.css',
    minify: true,

    // OPT-IN side outputs (default off). Generated files start with a
    // "generated by SenangStart CSS" marker; an existing file WITHOUT that
    // marker is never overwritten.
    aiContext: null,          // e.g. './.cursorrules'
    typescript: null          // e.g. './types/senang.d.ts'
  },

  // Build behavior
  build: {
    // true = warn instead of failing on invalid tokens (same as --ignore-invalid)
    ignoreInvalid: false
  },

  // Base reset styles (set false if you have your own reset/normalize)
  preflight: true,

  // Dark mode: 'media' (OS preference) | 'selector' (.dark class) | ['selector', '.custom']
  darkMode: 'media',

  // Theme customization
  theme: {
    // Emit every theme scale as CSS custom properties, not only the ones used.
    exposeAll: false,

    // Direct keys are deep-merged into the default scales:
    // spacing: { 'huge': '256px' },
    // colors: { 'brand': '#38BDF8' },

    // `extend` is the Tailwind-style equivalent and always wins over direct keys:
    extend: {
      // colors: { 'accent': '#EC4899' }
    }
  }
};
