#!/usr/bin/env node

/**
 * Generate schema/senangstart.config.schema.json (JSON Schema draft-07) from
 * src/config/defaults.js so descriptions, defaults and the list of theme
 * scales stay in sync with the code.
 *
 * Usage:
 *   node scripts/generate-schema.js            # write the schema
 *   node scripts/generate-schema.js --check    # exit 1 if the committed schema is stale
 *
 * JSON configs (senangstart.config.json) can opt into editor validation with
 *   { "$schema": "./node_modules/@bookklik/senangstart-css/schema/senangstart.config.schema.json" }
 */

import { writeFileSync, readFileSync, existsSync, mkdirSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');
const OUT = 'schema/senangstart.config.schema.json';

/** Human descriptions for theme scales (anything else gets a generic one). */
const THEME_SCALE_DESCRIPTIONS = {
  spacing: 'Spacing scale ("Natural Object" adjectives) used by p:, m:, g:, w:, h:, inset: … Values are CSS lengths.',
  radius: 'Border-radius scale used by rounded:.',
  shadow: 'Box-shadow scale used by shadow:.',
  fontSize: 'Font-size scale used by text-size:.',
  fontSizeLineHeight: 'Line-heights paired with fontSize keys (same keys).',
  fontWeight: 'Font-weight scale used by font:.',
  lineHeight: 'Line-height scale used by leading:.',
  screens: 'Breakpoints used as variant prefixes (tab:, max-tab:, tab-lap:). Values are min-width lengths or "print".',
  colors: 'Colour palette used by bg:, text:, border:, … Keys like "blue-500" form family-shade grids.',
  container: 'Max-widths for layout="container" per breakpoint (keys match screens).',
  zIndex: 'z-index scale used by z:.',
  blur: 'blur:/backdrop-blur: scale.',
  brightness: 'brightness: scale (numeric multipliers).',
  contrast: 'contrast: scale (numeric multipliers).',
  grayscale: 'grayscale: scale (percentages).',
  invert: 'invert: scale (percentages).',
  saturate: 'saturate: scale (numeric multipliers).',
  sepia: 'sepia: scale (percentages).',
  dropShadow: 'drop-shadow: scale.',
  backdropOpacity: 'backdrop-opacity: scale (0–1).',
  transitionProperty: 'transition: property groups.',
  animationDuration: 'duration:/animation-duration: scale.',
  animationDelay: 'delay:/animation-delay: scale.',
  perspective: 'perspective: scale.',
  placeholder: 'Placeholder text colour for form inputs.'
};

const scaleSchema = (name, def) => ({
  type: 'object',
  description: THEME_SCALE_DESCRIPTIONS[name] || `Theme scale "${name}".`,
  additionalProperties: { type: 'string' },
  ...(def && typeof def === 'object' ? { default: def } : {})
});

/**
 * Build the schema object from a (default) config.
 * @param {Object} defaults - defaultConfig
 * @returns {Object} JSON Schema draft-07
 */
export function buildSchema(defaults) {
  const theme = defaults.theme || {};
  const themeProperties = {};
  const scaleNames = [];
  for (const [key, value] of Object.entries(theme)) {
    if (key === 'extend' || key === 'exposeAll' || key === 'palette') continue;
    if (value && typeof value === 'object') {
      scaleNames.push(key);
      themeProperties[key] = scaleSchema(key, value);
    } else {
      themeProperties[key] = {
        type: typeof value === 'boolean' ? 'boolean' : 'string',
        description: THEME_SCALE_DESCRIPTIONS[key] || `Theme value "${key}".`,
        default: value
      };
    }
  }
  // Scales the definitions reference but the default theme may not declare
  for (const extra of ['lineHeight']) {
    if (!themeProperties[extra]) { scaleNames.push(extra); themeProperties[extra] = scaleSchema(extra); }
  }

  const themeScalesSchema = {
    type: 'object',
    description: 'Theme scales. Keys are the adjectives used in tokens; values are CSS values.',
    properties: Object.fromEntries(scaleNames.map(n => [n, { ...scaleSchema(n), default: undefined }])),
    additionalProperties: { type: 'object', additionalProperties: { type: 'string' } }
  };
  for (const v of Object.values(themeScalesSchema.properties)) delete v.default;

  return {
    $schema: 'http://json-schema.org/draft-07/schema#',
    $id: 'https://bookklik-technologies.github.io/senangstart-css/schema/senangstart.config.schema.json',
    title: 'SenangStart CSS configuration',
    description: 'Configuration for senangstart.config.{js,mjs,cjs,json}. Generated by scripts/generate-schema.js from src/config/defaults.js — do not edit by hand.',
    type: 'object',
    additionalProperties: false,
    properties: {
      $schema: {
        type: 'string',
        description: 'JSON Schema reference (JSON configs only), e.g. "./node_modules/@bookklik/senangstart-css/schema/senangstart.config.schema.json".'
      },
      content: {
        type: 'array',
        description: 'Glob patterns to scan for layout/space/visual attributes, relative to the project root. Prefix with "!" to negate. node_modules, .git and dist are ignored by default.',
        items: { type: 'string', minLength: 1 },
        default: defaults.content
      },
      safelist: {
        type: 'array',
        description: 'Tokens to always emit even when not found in content. Entries are raw tokens ("p:medium", "visual=bg:primary", "flex") or { attr, tokens } groups.',
        items: {
          oneOf: [
            { type: 'string', minLength: 1 },
            {
              type: 'object',
              required: ['attr', 'tokens'],
              additionalProperties: false,
              properties: {
                attr: { type: 'string', enum: ['layout', 'space', 'visual', 'interact', 'listens'] },
                tokens: { type: 'array', items: { type: 'string', minLength: 1 } }
              }
            }
          ]
        },
        default: defaults.safelist ?? []
      },
      prefix: {
        type: 'string',
        description: 'Attribute prefix: "ss" makes the attributes ss-layout / ss-space / ss-visual (unprefixed attributes are then ignored). Empty string disables.',
        default: defaults.prefix ?? ''
      },
      layers: {
        type: 'boolean',
        description: 'Wrap emitted CSS in cascade layers (@layer senangstart.theme, senangstart.base, senangstart.utilities).',
        default: defaults.layers ?? true
      },
      presets: {
        description: "Opt-in presets: ['prose', 'forms'], or { prose: { maxWidth: '70ch' }, forms: { accent: 'var(--c-primary)' } }.",
        oneOf: [
          { type: 'array', items: { type: 'string', enum: ['prose', 'forms'] } },
          { type: 'object', properties: { prose: { oneOf: [{ type: 'boolean' }, { type: 'object', properties: { maxWidth: { type: 'string' } } }] }, forms: { oneOf: [{ type: 'boolean' }, { type: 'object', properties: { accent: { type: 'string' }, border: { type: 'string' }, radius: { type: 'string' } } }] } }, additionalProperties: false }
        ],
        default: []
      },
      utilities: {
        type: 'object',
        description: 'Custom utilities. Key = utility name; value = { attr, css } for a keyword or { attr, template, scale, literals, enum, passthrough, numeric, arbitrary } for a valued utility. See docs/guide/plugins.md.',
        additionalProperties: {
          type: 'object',
          properties: {
            attr: { type: 'string', enum: ['layout', 'space', 'visual'], default: 'visual' },
            css: { type: 'string', description: 'Static declarations (keyword utility).' },
            template: { type: 'string', description: 'Declaration template with {value}.' },
            arbitraryTemplate: { type: 'string' },
            scale: { type: 'string', description: 'theme key whose entries are the accepted values.' },
            literals: { type: 'object', additionalProperties: { type: 'string' } },
            enum: { type: 'object', additionalProperties: { type: 'string' } },
            passthrough: { type: 'boolean' },
            arbitrary: { type: 'boolean' },
            numeric: { type: 'object', properties: { unit: { type: 'string' }, divide: { type: 'number' } } }
          }
        }
      },
      variants: {
        type: 'object',
        description: 'Custom variants. "&:hover, &:focus" (state, alternatives become :is()), "[data-theme=dark] &" (ancestor), or "@media (…)" / "@supports (…)".',
        additionalProperties: { type: 'string' }
      },
      plugins: {
        type: 'array',
        description: 'Functional plugins (JS configs only): ({ addUtilities, addVariants, addKeyframes, addAnimation, theme }) => void.',
        items: {}
      },
      output: {
        type: 'object',
        description: 'Output files.',
        additionalProperties: false,
        properties: {
          css: { type: 'string', minLength: 1, description: 'Path of the generated stylesheet.', default: defaults.output?.css },
          minify: { type: 'boolean', description: 'Minify the generated CSS.', default: defaults.output?.minify ?? false },
          aiContext: {
            description: 'Opt-in AI context file path (e.g. "./.cursorrules"). null or false disables.',
            oneOf: [{ type: 'string', minLength: 1 }, { type: 'null' }, { type: 'boolean', enum: [false] }],
            default: defaults.output?.aiContext ?? null
          },
          typescript: {
            description: 'Opt-in project-local TypeScript definitions path (e.g. "./types/senang.d.ts"). The file augments React/Vue/Svelte/Solid/Preact/Astro with your theme. null or false disables; prefer importing "@bookklik/senangstart-css/react" (etc.) when you use the default theme.',
            oneOf: [{ type: 'string', minLength: 1 }, { type: 'null' }, { type: 'boolean', enum: [false] }],
            default: defaults.output?.typescript ?? null
          }
        },
        default: defaults.output
      },
      darkMode: {
        description: 'Dark-mode strategy: "media" (prefers-color-scheme), "selector" or "class" (.dark ancestor), ["selector", ".custom"] for a custom ancestor selector, or false to disable dark: variants.',
        oneOf: [
          { type: 'string', enum: ['media', 'selector', 'class'] },
          {
            type: 'array',
            items: [{ type: 'string', enum: ['selector'] }, { type: 'string', minLength: 1 }],
            minItems: 2,
            maxItems: 2
          },
          { type: 'boolean', enum: [false] }
        ],
        default: defaults.darkMode
      },
      preflight: {
        type: 'boolean',
        description: 'Include the opinionated base reset styles.',
        default: defaults.preflight
      },
      build: {
        type: 'object',
        description: 'Build behaviour.',
        additionalProperties: false,
        properties: {
          ignoreInvalid: {
            type: 'boolean',
            description: 'Warn instead of failing (exit code 1) when invalid tokens are found. Same as --ignore-invalid.',
            default: defaults.build?.ignoreInvalid ?? false
          }
        },
        default: defaults.build
      },
      ignoreInvalid: {
        type: 'boolean',
        description: 'Top-level alias of build.ignoreInvalid.',
        default: defaults.build?.ignoreInvalid ?? false
      },
      theme: {
        type: 'object',
        description: 'Theme customisation. Direct scale keys are deep-merged into the defaults; theme.extend is applied afterwards (Tailwind-style) and always wins.',
        additionalProperties: { type: 'object', additionalProperties: { type: 'string' } },
        properties: {
          ...themeProperties,
          extend: { ...themeScalesSchema, description: 'Additive overrides merged after the direct theme keys.' },
          palette: {
            type: 'string',
            enum: ['hex', 'oklch'],
            description: "Colour palette: 'hex' (default, Tailwind v3 values) or 'oklch' (Tailwind v4 values; semantic colours follow).",
            default: theme.palette ?? 'hex'
          },
          exposeAll: {
            type: 'boolean',
            description: 'Emit every theme scale as CSS custom properties, not only the ones that are used.',
            default: theme.exposeAll ?? false
          }
        }
      },
      extend: {
        ...themeScalesSchema,
        description: 'Deprecated alias of theme.extend.',
        deprecated: true
      }
    },
    definitions: {
      themeScale: { type: 'object', additionalProperties: { type: 'string' } },
      themeScaleName: { type: 'string', enum: scaleNames }
    }
  };
}

export async function buildSchemaFromDefaults() {
  const { defaultConfig } = await import('../src/config/defaults.js');
  return buildSchema(defaultConfig);
}

async function main() {
  const check = process.argv.includes('--check');
  const schema = await buildSchemaFromDefaults();
  const content = JSON.stringify(schema, null, 2) + '\n';
  const outPath = join(root, OUT);
  const current = existsSync(outPath) ? readFileSync(outPath, 'utf-8') : null;

  if (check) {
    if (current !== content) {
      console.error(`\u2717 ${OUT} is out of date (run: npm run generate:schema)`);
      process.exit(1);
    }
    console.log(`\u2713 ${OUT} is up to date`);
    return;
  }
  if (current === content) {
    console.log(`\u2713 ${OUT} (unchanged)`);
    return;
  }
  mkdirSync(dirname(outPath), { recursive: true });
  writeFileSync(outPath, content, 'utf-8');
  console.log(`\u2713 Generated ${OUT}`);
}

const isMain = process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1];
if (isMain) {
  main().catch(err => {
    console.error('\u2717 Failed to generate schema:', err.message);
    process.exit(1);
  });
}
