/**
 * SenangStart CSS - AI Context Generator
 * Generates .cursorrules or ai-context.md for LLM assistance
 */

/**
 * Generate AI context file content
 * @param {Object} config - Configuration object
 * @returns {string} - AI context markdown content
 */
export function generateAIContext(config) {
  const { theme } = config;
  
  return `# SenangStart CSS - AI Context Guide

> This file helps AI assistants understand the SenangStart CSS framework.

## Philosophy
"Speak Human. Compile to Logic."
Use natural adjectives instead of arbitrary numbers.

## Tri-Attribute Syntax

| Attribute | Purpose | Example |
|-----------|---------|---------|
| \`layout\` | Structure & position | \`layout="flex col center"\` |
| \`space\` | Sizing & spacing | \`space="p:medium g:small"\` |
| \`visual\` | Colors & appearance | \`visual="bg:white rounded:big"\` |

## Spacing Scale (Natural Objects)

| Keyword | Size | Mental Model |
|---------|------|--------------|
| \`none\` | ${theme.spacing.none} | No space |
| \`tiny\` | ${theme.spacing.tiny} | Pebble - Borders, offsets |
| \`small\` | ${theme.spacing.small} | Matchbox - Group related items |
| \`medium\` | ${theme.spacing.medium} | Smartphone - Standard default |
| \`big\` | ${theme.spacing.big} | Laptop - Separate sections |
| \`giant\` | ${theme.spacing.giant} | Door - Layout divisions |
| \`vast\` | ${theme.spacing.vast} | House - Hero sections |

## Natural Language Mapping

When users say... | Do this...
------------------|------------
"tighten it up" | Scale DOWN (medium → small → tiny)
"give it air" / "breathe" | Scale UP (medium → big → giant)
"make it pop" | Add \`shadow:big\`, increase \`rounded\`
"subtle" | Use \`shadow:small\`, \`rounded:small\`
"compact" | Use \`p:small g:tiny\`
"spacious" | Use \`p:big g:medium\` or larger

## Layout Keywords

- **Display:** \`flex\`, \`grid\`, \`block\`, \`hidden\`
- **Direction:** \`row\`, \`col\`, \`row-reverse\`, \`col-reverse\`
- **Alignment:** \`center\`, \`between\`, \`start\`, \`end\`
- **Position:** \`absolute\`, \`relative\`, \`fixed\`, \`sticky\`
- **Z-Index:** \`z:base\`, \`z:low\`, \`z:mid\`, \`z:high\`, \`z:top\`

## Space Syntax

Pattern: \`[breakpoint]:[property]:[scale]\`

- \`p:medium\` → padding: 16px
- \`m-b:big\` → margin-bottom: 32px
- \`g:small\` → gap: 8px
- \`tab:p:big\` → padding: 32px on tablet+
- \`w:[350px]\` → width: 350px (escape hatch)

## Visual Keywords

- **Background:** \`bg:white\`, \`bg:primary\`, \`bg:[#hex]\`
- **Text:** \`text:dark\`, \`text:grey\`, \`text-size:big\`
- **Font:** \`font:bold\`, \`font:medium\`, \`font:normal\`
- **Rounded:** \`rounded:small\`, \`rounded:medium\`, \`rounded:big\`, \`rounded:round\`
- **Shadow:** \`shadow:small\`, \`shadow:medium\`, \`shadow:big\`

## Responsive Prefixes

| Prefix | Breakpoint |
|--------|------------|
| \`mob:\` | ${theme.screens.mob}+ |
| \`tab:\` | ${theme.screens.tab}+ |
| \`lap:\` | ${theme.screens.lap}+ |
| \`desk:\` | ${theme.screens.desk}+ |

## Color Palette

${Object.entries(theme.colors).map(([key, value]) => `- \`${key}\`: ${value}`).join('\n')}

## Common Patterns

### Card
\`\`\`html
<div
  layout="flex col"
  space="p:medium"
  visual="bg:white rounded:big shadow:medium"
>
  Content
</div>
\`\`\`

### Centered Container
\`\`\`html
<div space="max-w:[1200px] m-x:auto p-x:medium">
  Content
</div>
\`\`\`

### Navigation
\`\`\`html
<nav
  layout="flex between center fixed z:top"
  space="w:[100%] p-x:big p-y:small"
  visual="bg:white shadow:small"
>
  Navigation items
</nav>
\`\`\`

---
*Generated by SenangStart CSS*
`;
}

export default { generateAIContext };
